import { SpeakerPersona, StylePreset, TextSample } from '../types';

export const PERSONAS: SpeakerPersona[] = [
  {
    id: 'ratih',
    name: 'Mbak Ratih',
    voice: 'Kore',
    gender: 'Wanita',
    tone: 'Ramah, Hangat & Artikulatif',
    tagline: 'Penjelas Konsep yang Menyenangkan',
    description: 'Suara jernih dengan tutur kata mengalir santai namun sangat jelas, layaknya rekan kerja atau guru privat yang menerangkan dengan penuh kesabaran.',
    avatarBg: 'from-amber-600 to-rose-700',
    bestFor: 'Tutorial, edukasi konsep, penjelasan sains populer, panduan langkah demi langkah',
  },
  {
    id: 'dimas',
    name: 'Mas Dimas',
    voice: 'Puck',
    gender: 'Pria',
    tone: 'Santai, Lugas & Bersahabat',
    tagline: 'Teman Diskusi yang Komunikatif',
    description: 'Gaya bicara luwes, intonasi lincah dan tidak kaku, terasa seperti teman sebaya yang sedang menceritakan hal menarik saat bersantai.',
    avatarBg: 'from-blue-600 to-teal-700',
    bestFor: 'Teknologi praktis, tips keseharian, obrolan santai, gaya hidup',
  },
  {
    id: 'budi',
    name: 'Pak Budi',
    voice: 'Fenrir',
    gender: 'Pria',
    tone: 'Matang, Bijak & Menenangkan',
    tagline: 'Narator Berpengalaman & Berwibawa',
    description: 'Nada bicara hangat dengan wibawa kebapakan yang menentramkan jiwa pendengar, setiap kalimat diucapkan dengan bobot dan penghayatan yang dalam.',
    avatarBg: 'from-emerald-700 to-stone-800',
    bestFor: 'Sejarah kebudayaan, kuliah pengantar, sastra nusantara, panduan mendalam',
  },
  {
    id: 'dewi',
    name: 'Ibu Dewi',
    voice: 'Zephyr',
    gender: 'Wanita',
    tone: 'Lembut, Santun & Teduh',
    tagline: 'Penutur Reflektif yang Menginspirasi',
    description: 'Tutur kata sopan, intonasi anggun dengan ritme tenang yang memikat dan mudah meresap ke dalam hati pendengar.',
    avatarBg: 'from-purple-700 to-pink-700',
    bestFor: 'Refleksi hidup, kisah inspiratif, dongeng nusantara, psikologi ringan',
  },
  {
    id: 'bayu',
    name: 'Mas Bayu',
    voice: 'Charon',
    gender: 'Pria',
    tone: 'Bariton Rendah, Tegas & Terpercaya',
    tagline: 'Penjelas Lugas Tanpa Berbelit',
    description: 'Artikulasi mantap dan artikulatif dengan resonansi vokal dalam, menyajikan fakta dan penjelasan secara meyakinkan.',
    avatarBg: 'from-stone-700 to-slate-900',
    bestFor: 'Eksplanasi ilmiah, wawasan industri, ringkasan eksekutif, dokumenter',
  },
];

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'edukasi-santai',
    label: 'Penjelasan Edukasi Ramah',
    description: 'Gaya tutur membimbing yang bersahabat, tempo stabil, intonasi menyenangkan.',
    promptAddon: 'Intonasi pengajar ramah yang sedang menjelaskan konsep dengan sabar dan menyenangkan.',
    icon: 'GraduationCap',
  },
  {
    id: 'storyteller',
    label: 'Pencerita Alami (Storyteller)',
    description: 'Penuh penjiwaan rasa dan dinamika nada seperti mendongengkan kisah langsung.',
    promptAddon: 'Gaya narator pencerita yang hidup, memiliki jeda dramaturgi alami dan artikulasi hangat.',
    icon: 'Sparkles',
  },
  {
    id: 'lugas-ringkas',
    label: 'Eksplanasi Lugas & Praktis',
    description: 'Artikulasi tegas, tidak bertele-tele, langsung tepat sasaran ke inti pokok bahasan.',
    promptAddon: 'Penyampaian lugas dan jelas, artikulasi teratur tanpa berbelit-belit.',
    icon: 'Compass',
  },
  {
    id: 'obrolan-akrab',
    label: 'Obrolan Santai Nusantara',
    description: 'Mengalir sangat luwes seperti sedang bertukar pikiran di kedai kopi.',
    promptAddon: 'Gaya bertutur santai dan sangat bersahabat, tidak formal berlebihan, hangat seperti sahabat bicara langsung.',
    icon: 'Coffee',
  },
];

export const SAMPLE_TEXTS: TextSample[] = [
  {
    id: 'langit-senja',
    title: 'Kenapa Langit Senja Berubah Menjadi Jingga Merah?',
    category: 'Sains Populer',
    personaId: 'ratih',
    styleId: 'edukasi-santai',
    explanation: 'Penjelasan fenomena hamburan cahaya dengan bahasa tutur yang renyah dan mudah dimengerti siapa saja.',
    text: 'Pernah tidak kamu bertanya-tanya, kenapa saat siang hari langit kita berwarna biru cerah, tapi begitu matahari mulai terbenam di ufuk barat, warnanya perlahan berubah jadi jingga kemerahan? <breath> Nah, rahasianya ada pada perjalanan berkas sinar matahari saat menembus lapisan atmosfer bumi kita. Di siang hari, jarak yang ditempuh cahaya lebih pendek, sehingga gelombang warna biru yang pendek mudah berhamburan ke segala arah. Tapi saat senja tiba, posisi matahari berada sangat rendah di cakrawala. Cahayanya harus melintasi lapisan udara yang jauh lebih tebal. Akibatnya, sebagian besar warna biru habis terhambur di kejauhan, dan hanya warna merah serta jingga dengan gelombang lebih panjanglah yang berhasil sampai ke pandangan mata kita.',
  },
  {
    id: 'kopi-gayo',
    title: 'Menyelami Rahasia Aroma Kopi Dataran Tinggi Gayo',
    category: 'Kekayaan Nusantara',
    personaId: 'budi',
    styleId: 'storyteller',
    explanation: 'Penjelasan budaya dan rasa kopi nusantara dengan intonasi kebapakan yang hangat dan kaya rasa bahasa.',
    text: 'Bagi masyarakat kita di tanah air, secangkir kopi di pagi hari bukan sekadar minuman penawar kantuk, melainkan teman berbincang dan perekat kebersamaan. <breath> Di ujung barat Nusantara, tepatnya di dataran tinggi Gayo, biji kopi arabika tumbuh di lereng pegunungan berhawa sejuk yang diselimuti kabut pagi. Tanah vulkanik yang subur berpadu dengan ketelatenan para petani lokal merawat setiap tangkai pohon kopi. <breath> Hasilnya adalah cita rasa yang sangat khas, aroma bunganya harum memikat, ada sentuhan rempah yang lembut di tenggorokan, dan tingkat keasamannya pun terasa seimbang. Setiap tegukan seolah membawa kita merasakan sejuknya angin perbukitan Aceh.',
  },
  {
    id: 'kebiasaan-fokus',
    title: 'Trik Sederhana Agar Pikiran Tidak Mudah Buyar',
    category: 'Tips Keseharian',
    personaId: 'dimas',
    styleId: 'obrolan-akrab',
    explanation: 'Gaya santai menjelaskan cara menjaga konsentrasi kerja tanpa merasa digurui.',
    text: 'Sering merasa baru mulai kerja sepuluh menit, tiba-tiba tangan sudah refleks membuka hal lain di layar? Tenang, kamu tidak sendirian, hampir semua orang mengalaminya. <breath> Masalahnya bukan karena kita malas, melainkan otak kita memang mudah tergiur oleh rangsangan baru. Nah, cara paling manjur mengatasinya ternyata sangat sederhana. Mulai hari ini, coba jangan paksa diri untuk fokus berjam-jam sekaligus. Cukup pasang pengingat selama dua puluh lima menit saja untuk menyelesaikan satu tugas kecil. Singkirkan benda-benda yang mengganggu di sekitar meja. Begitu waktu selesai, baru beri diri kamu hadiah istirahat sebentar. Rasakan sendiri betapa jauh lebih ringannya pikiran kita.',
  },
  {
    id: 'tidur-nyenyak',
    title: 'Apa yang Terjadi di Tubuh Kita Saat Tertidur Lelap?',
    category: 'Kesehatan & Refleksi',
    personaId: 'dewi',
    styleId: 'edukasi-santai',
    explanation: 'Penjelasan biologi tubuh yang meneduhkan dan mengajak pendengar lebih menghargai waktu istirahat.',
    text: 'Banyak orang mengira ketika kita tertidur pulas, tubuh kita berhenti bekerja sepenuhnya. Padahal kenyataannya justru sebaliknya. <breath> Di saat kita terlelap dalam keheningan malam, tubuh kita sebenarnya sedang menyalakan sistem pemulihan terbaiknya. Otak kita sibuk merapikan berkas-berkas ingatan dari seharian yang lalu, membuang sisa racun sel, sementara otot-otot yang lelah diperbaiki kembali perlahan-lahan. Maka dari itu, memberikan waktu tidur yang cukup bukan tanda kita menyia-nyiakan waktu, melainkan bentuk kasih sayang paling tulus untuk menjaga raga dan jiwa kita tetap bugar esok hari.',
  },
  {
    id: 'teknologi-ai',
    title: 'Mengenal Cara Komputer Belajar Mengerti Bahasa Manusia',
    category: 'Wawasan Modern',
    personaId: 'bayu',
    styleId: 'lugas-ringkas',
    explanation: 'Penjelasan konsep teknologi kecerdasan buatan dalam bahasa Indonesia yang jernih dan terstruktur.',
    text: 'Bagaimana mungkin mesin komputer yang hanya mengenali angka satu dan nol bisa memahami kalimat yang kita ucapkan sehari-hari? Inti dari proses ini terletak pada pengenalan pola. <breath> Model komputasi modern membaca jutaan susunan kalimat, mempelajari bagaimana kata-kata saling terhubung, serta menebak kata berikutnya berdasarkan konteks pembicaraan. Mesin tidak memiliki perasaan seperti manusia, tetapi mampu memetakan keterkaitan makna dengan sangat cermat. Hasilnya adalah kemampuannya merespons dan membantu pekerjaan manusia dengan jauh lebih luwes.',
  },
];
